name: Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7"]
        dependency: ["django","none"]

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        if [ ${{ matrix.dependency }} == django ]; then pip install Django<2.2; fi
        pip install -r requirements-dev.txt
        pip install codecov pyOpenSSL


    - name: Run tests
      run: |
        make test check coverage
        codecov

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        user: ${{ secrets.pypi_user }}
        password: ${{ secrets.pypi_password }}
